### ISSUE TITLE
AssignUserToTask use-case: first step FindTaskToAssign

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/kira#1]
## What needs to be done?

We need to find tasks that can be assigned.
Currently we care about only:
1. issues
2. status: opened
3. assignee: nil

Any other things are not in scope.
Later, we will prioritise them based on weight.

## Technical details

1. Take a look at https://gitlab.com/wemake.services/kira/blob/master/lib/kira/usecases/assign_user_to_task.ex

## How to complete

Please, read below: [how to implement a feature](https://wemake.services/meta/rsdp/closing-issues#how-to-complete-a-feature).

**Comment by sobolevn** [comment]
@rtrv ping

**Comment by rtrv** [comment]
@sobolevn I recreated the request from GitLab here and started to resolve TODOs there. Are there any changes I need to know related to moving to GitHub?

**Comment by sobolevn** [comment]
Nope
