### ISSUE TITLE
Create OAuth login mechanism via Gitlab

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/kira#15]
We need to implement OAuth login via Gitlab.
We can use `ueberauth` for that.

Later this feature will be required to create `working/not-working` buttons.

Scope:
1. Controller to work with auth requests
2. Modifications to `Kira.Accounts.Entities.User` that are required for auth to work
3. Integration tests that auth is working

**Comment by mgrishko** [comment]
I'll do it
upd. - next week, till 09.06

**Comment by rsolovjov** [comment]
Was this issue completed? I saw dependencies in mix and config files

**Comment by sobolevn** [comment]
Yeap: https://github.com/wemake-services/kira/blob/master/lib/kira_web/controllers/auth_controller.ex

Just not closed 🙂
