### ISSUE TITLE
Handle close of merge request

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/kira#20]
## What needs to be done?

We need to handle merge request close requests. 
Docs: https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#merge-request-events

Here: https://github.com/wemake-services/kira/blob/master/lib/kira_web/webhooks/merge_request_webhook.ex#L24

Example with issues: https://github.com/wemake-services/kira/blob/master/lib/kira_web/webhooks/issue_webhook.ex#L23

Scope:
1. Controller fix
2. New usecase
3. New command
4. Integration test that this webhook works

**Comment by rsolovjov** [comment]
I'll do it at the weekend.
