### ISSUE TITLE
Handle merge request update requests

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/kira#21]
## What needs to be done?

We need to update internal state of merge requests when they are update on gitlab. We receive a webhook with the change.
Docs: https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#merge-request-events

We need to save updated data.
Here: https://github.com/wemake-services/kira/blob/master/lib/kira_web/webhooks/merge_request_webhook.ex#L24

Example with issues: https://github.com/wemake-services/kira/blob/master/lib/kira_web/webhooks/issue_webhook.ex#L23

Scope:

1. Controller fix
2. New usecase
3. New command
4. Integration test that this webhook works

**Comment by lyk0rian** [comment]
I'll do it

**Comment by lyk0rian** [comment]
JFYI, I've made some research and found GitLab won't trigger any webhook in case of merge request deletion. Only merge request closing will trigger an event. So, in case someone decide to delete a merge request, we can't update information about it through webhooks.

**Comment by sobolevn** [comment]
@lyk0rian thanks a lot for this information. It is valuable.
